EXE = ejercicio3a ejercicio3b ejer4a ejer4b ejercicio6 ejercicio8 ejercicio10conSleep ejercicio10sinSleep ejercicio10sincronizado 

all: $(EXE)

ejercicio3a : ejercicio3a.c
	gcc -o $@ $< -lm -lpthread


ejercicio3b: ejercicio3b.c
	gcc -o $@ $< -lm -lpthread

ejer4a: ejer4a.c
	gcc -o $@ $<  -lpthread


ejer4b: ejer4b.c
	gcc -o $@ $< -lpthread

ejercicio6: ejercicio6.c
	gcc -o $@ $< -lpthread

ejercicio8: ejercicio8.c
	gcc -o $@ $< -lpthread


ejercicio10conSleep: ejercicio10conSleep.c
	gcc -o $@ $<  -lpthread

ejercicio10sinSleep: ejercicio10sinSleep.c
	gcc -o $@ $<  -lpthread

ejercicio10sincronizado: ejercicio10sincronizado.c
	gcc -o $@ $<  -lpthread
 

