all: ejercicio4a ejercicio4b ejercicio4SinHuerfanos ejercicio5a ejercicio5b ejercicio6 ejercicio8 ejercicio9

ejercicio4a: ejercicio4a.c
	gcc -o ejercicio4a $^

ejercicio4b: ejercicio4b.c
	gcc -o ejercicio4b $^

ejercicio4SinHuerfanos: ejercicio4SinHuerfanos.c
	gcc -o ejercicio4SinHuerfanos $^

ejercicio5a: ejercicio5a.c
	gcc -o ejercicio5a $^

ejercicio5b: ejercicio5b.c
	gcc -o ejercicio5b $^

ejercicio6: ejercicio6.c
	gcc -o ejercicio6 $^

ejercicio8: ejercicio8.c
	gcc -o ejercicio8 $^

ejercicio9: ejercicio9.c
	gcc -o ejercicio9 $^

clean:
	rm -f *.o *~ ejercicio4a ejercicio4b ejercicio4SinHuerfanos ejercicio5a ejercicio5b ejercicio6 ejercicio8 ejercicio9
